In [26]:
sites = ["GAGGTAAAC", "TCCGTAAGC", "CAGGTTGGA", "ACAGTCAGC", "TAGGTCAGC",
         "CAGGTCAGC", "CAGGTCGAT", "CAGGTCAGC", "CAGGTCAGC", "CAGGTTGGC"]

In [27]:
import numpy as np

In [28]:
def position_frequency_matrix(seq: list[str]):
    # переводим список строк в список списков -> np.array
    seq = np.array([list(x) for x in seq])

    nucleotides = np.array(['A', 'T', 'G', 'C'])

    # для каждого нуклеотида считаем частоту его встречаемости (numpy поэлементно сравнивает каждый элемент нашей матрицы с нуклеотидом ->
    # получаем матрицу из нулей и единиц
    count_matrix = np.array([
        np.sum(seq == base, axis=0) for base in nucleotides
    ])
    
    return count_matrix


def position_probability_matrix(pfm: np.ndarray|list[list[int]], alpha=0.1):
    pfm = pfm + alpha
    ppm = pfm / np.sum(pfm, axis = 0)
    return ppm


def position_weight_matrix(ppm: np.ndarray|list[list[int|float]],
                          background = np.array([0.295, 0.295, 0.205, 0.205])):
    background = background.reshape(4, -1)
    pwm = np.log2(ppm / background)
    return pwm

In [29]:
pfm = position_frequency_matrix(sites)
print(pfm)

ppm = position_probability_matrix(pfm)
print(ppm)

pwm = position_weight_matrix(ppm)
print(pwm)

score_max = np.sum(np.max(pwm, axis = 0))
score_min = np.sum(np.min(pwm, axis = 0))

# мне не хватило интеллекта реализовать восстановление максимальной последотвальности с помощью броадкастинга без циклов
seq_max = []
seq_min = []
let = ['A', 'T', 'G', 'C']
for i in range(len(pwm[0])):
    ind_max = np.argmax(pwm[:, i])
    seq_max.append(let[ind_max])

    ind_min = np.argmin(pwm[:, i])
    seq_min.append(let[ind_min])

print(f'минимальный скор: {score_min}, последовательность с минимальным скором: {seq_min}')
print(f'максимальный скор: {score_max}, последовательность с минимальным скором: {seq_max}')
    



[[ 1  8  1  0  0  2  7  2  1]
 [ 2  0  0  0 10  2  0  0  1]
 [ 1  0  8 10  0  0  3  8  0]
 [ 6  2  1  0  0  6  0  0  8]]
[[0.10576923 0.77884615 0.10576923 0.00961538 0.00961538 0.20192308
  0.68269231 0.20192308 0.10576923]
 [0.20192308 0.00961538 0.00961538 0.00961538 0.97115385 0.20192308
  0.00961538 0.00961538 0.10576923]
 [0.10576923 0.00961538 0.77884615 0.97115385 0.00961538 0.00961538
  0.29807692 0.77884615 0.00961538]
 [0.58653846 0.20192308 0.10576923 0.00961538 0.00961538 0.58653846
  0.00961538 0.00961538 0.77884615]]
[[-1.47979496  1.40062343 -1.47979496 -4.93922658 -4.93922658 -0.54690915
   1.21052054 -0.54690915 -1.47979496]
 [-0.54690915 -4.93922658 -4.93922658 -4.93922658  1.71898491 -0.54690915
  -4.93922658 -4.93922658 -1.47979496]
 [-0.95470391 -4.41413553  1.92571447  2.24407595 -4.41413553 -4.41413553
   0.54006078  1.92571447 -4.41413553]
 [ 1.5166018  -0.02181811 -0.95470391 -4.41413553 -4.41413553  1.5166018
  -4.41413553 -4.41413553  1.92571447]]
минимальны

In [ ]:
# полученные мин макс последовательности норм согласуются с частотами и здравым смыслом